# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.1'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Rg.Plugins.Popup/Rg.Plugins.Popup.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'Rg.Plugins.Popup/Rg.Plugins.Popup.csproj'
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: 'off'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '*.nupkg'
    TargetFolder: '$(Pipeline.Workspace)\artifacts'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\artifacts'
    artifact: 'pacakge'
    publishLocation: 'pipeline'




